services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    network_mode: host
    volumes:
      - ./certs:/etc/nginx/certs
      - ./conf.d:/etc/nginx/conf.d
      - ./conf/nginx.conf:/etc/nginx/nginx.conf              #映射配置文件入口文件
      - ./html:/usr/share/nginx/html                         #静态资源根目录挂载
      - ./logs:/var/log/nginx                                #日志文件挂载
    restart: always